Adicionado toda as tabelas para revisao.
Veras-D/Gerenciador_Animais_APAM pull request #8
Opened 2024-07-26 14:15 UTC by ribeirowillian

@Veras-D Verificar se e esse o caminho correto, para depois eu criar as funções do CRUD.

2024-07-26 16:09 UTC, Veras-D requested changes
Please, fix indentation too

2024-07-26 16:09 UTC, Veras-D commented on src/Models/Repository/db.py
> +		self.results_castra = self.db_execute("SELECT * FROM animal_adotante")
self.results_animal_adotante

2024-07-26 16:09 UTC, Veras-D commented on src/Models/Repository/db.py
> +		self.results_adocao = self.db_execute("SELECT * FROM lar_temporario")
self.results_lar_temporario

2024-07-26 16:09 UTC, Veras-D commented on src/Models/Repository/db.py
> +			            foto BLOB,
add temperamento, status, castrado
remove data castração
change this:
			            idade_anos INTEGER,
			            idade_meses INTEGER,

2024-07-26 16:09 UTC, Veras-D commented on src/Models/Repository/db.py
> +               			name_animal TEXT NOT NULL,
remove name_animal

2024-07-26 16:09 UTC, Veras-D commented on src/Models/Repository/db.py
> +						nome_protetor TEXT NOT NULL,
remove nome_proteto

2024-07-26 16:09 UTC, Veras-D commented on src/Models/Repository/db.py
> +			self.db_execute('''CREATE TABLE IF NOT EXISTS castracao
add id_castracao
remove castrado

2024-07-26 16:09 UTC, Veras-D commented on src/Models/Repository/db.py
> +			self.db_execute('''CREATE TABLE IF NOT EXISTS obito
add id_obito

2024-07-26 19:11 UTC, ribeirowillian commented on src/Models/Repository/db.py
> +			            foto BLOB,
add temperamento, status, castrado - CHECK
remove data castração - ESSE NÃO EXISTIA
change this:
idade_anos INTEGER, - ALTERADO PARA TEXT
idade_meses INTEGER, - ALTERADO PARA TEXT

2024-07-26 19:13 UTC, ribeirowillian commented on src/Models/Repository/db.py
> +               			name_animal TEXT NOT NULL,
Removido

2024-07-26 19:15 UTC, ribeirowillian commented on src/Models/Repository/db.py
> +			self.db_execute('''CREATE TABLE IF NOT EXISTS castracao
Pq colocar id_castracao? Sendo q ele vai ser castrado uma unica vez na vida, ai seria 1:1 mesmo. O campo castrado que está no tabela animal, não acha valido deixar nessa tebela?

2024-07-26 19:16 UTC, ribeirowillian commented on src/Models/Repository/db.py
> +			self.db_execute('''CREATE TABLE IF NOT EXISTS obito
A do obito é a mesma coisa, se ele morrer, vai ser uma vez só, ai é 1:1

2024-07-29 20:45 UTC, closed without merging

2024-07-29 20:45 UTC, Veras-D commented
fisish review